# Generated by Django 4.0 on 2021-12-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('written_by', models.CharField(max_length=100)),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customauthentication.user')),
            ],
        ),
    ]
