# Generated by Django 4.0 on 2021-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
    ]
