# Generated by Django 4.0 on 2021-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauthentication', '0003_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
